services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  metadata:
    image: metadata-svc:latest
    ports:
      - '8000:8000'
volumes:
  db:
    driver: local
