{{- if .Values.use_external_secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: metadata-service-secrets
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: gcp-backend
    kind: ClusterSecretStore
  target:
    name: {{ default "metadata-service-secrets" .Values.secret_name }}
  data:
    - secretKey: .secrets.toml
      remoteRef:
        key: {{ default "metadata-service-secrets" .Values.secret_name }}
{{- end }}