{{ if .Values.create_secret -}}
---
apiVersion: v1
data:
  .secrets.toml: {{ .Values.secretContents }}
kind: Secret
metadata:
  name: rag-indexer-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
{{ end -}}