kind: Service
apiVersion: v1
metadata:
  name: metadata-service
  namespace: {{ .Values.namespace }}
spec:
    type: NodePort
    selector:
        app: metadata-service
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000