[dev-localhost]
# Use this to run the app in a local environment (for debugging, with local database)
# set ENV_FOR_DYNACONF=dev-localhost in .env file
DATABASE_USER = "postgres"
DATABASE_PASSWORD = "123456"
DATABASE_NAME = "metadata_service"
DATABASE_HOST = "localhost"
DATABASE_PORT = "5433"
LOG_LEVEL = "debug"
CONFIG.ANALYTICS_FOLDER = ""
LOG_SANE = "false"
