[dev-compose]
# Use this to run the app in a docker-compose environment
# set ENV_FOR_DYNACONF=dev-compose in .env file
DATABASE_USER = "postgres"
DATABASE_PASSWORD = "postgres"
DATABASE_NAME = "postgres"
DATABASE_HOST = "db"
DATABASE_PORT = "5432"
LOG_LEVEL = "debug"
CONFIG.ANALYTICS_FOLDER = ""
LOG_SANE = "false"
